#pragma once

#include <QObject>
#include <QString>
#include <QQmlComponent>

#include "buildinfo.h"  // generated by CMake

class AppBuildInfo : public QObject
{
    Q_OBJECT
    QML_ELEMENT
    QML_SINGLETON

    Q_PROPERTY(QString version   READ version   CONSTANT)
    Q_PROPERTY(QString date      READ date      CONSTANT)
    Q_PROPERTY(QString type      READ type      CONSTANT)
    Q_PROPERTY(QString os        READ os        CONSTANT)
    Q_PROPERTY(QString arch      READ arch      CONSTANT)
    Q_PROPERTY(QString compiler  READ compiler  CONSTANT)
    Q_PROPERTY(QString qtVersion READ qtVersion CONSTANT)

public:
    explicit AppBuildInfo(QObject *parent = nullptr)
        : QObject(parent) {}

public:
    QString version()   const { return BUILDINFO_VERSION; }
    QString date()      const { return BUILDINFO_DATE; }
    QString type()      const { return BUILDINFO_TYPE; }
    QString os()        const { return BUILDINFO_OS; }
    QString arch()      const { return BUILDINFO_ARCH; }
    QString compiler()  const { return BUILDINFO_COMPILER; }
    QString qtVersion() const { return BUILDINFO_QT_VERSION; }
};
